select MONTH(mes) MES,CLICK_ESTADO,FILIAL,MUNICIPIO,PROTOCOLO_CLICK PROTOCOLO,STATUS_OS_ATUAL,PERIMETRO_NOVA_OI,PERIMETRO_VTAL from BOV_VENDA_LIQUIDA_FTTH
where MONTH(mes) = 09 and year(mes) = 2021 and FLAG_CADEIA = 's'

SELECT * FROM (
SELECT NUMERO_PEDIDO,CODIGO_PENDENCIA,DATA_ABERTURA_ATIVIDADE,DATA_FECHAMENTO_ATIVIDADE,DATA_ABERTURA_OS,DATA_FECHAMENTO_OS 
FROM SIDARA_OMR_TRAMITACAO_FTTH)A
INNER JOIN (SELECT NUMERO_PEDIDO FROM SIDARA_OMR_TRAMITACAO_FTTH
WHERE  MONTH(DATA_ABERTURA_OS) = 09 and year(DATA_ABERTURA_OS) = 2021
AND CODIGO_PENDENCIA=7038) B ON A.NUMERO_PEDIDO = B.NUMERO_PEDIDO 